### ISSUE TITLE
NoneType issue

### ISSUE THREAD

**Issue by Jonas-Johnson** [Jonas-Johnson/FizzBuzz#2]
While testing a non integer character in the setup portion I found that if you put in a non integer, you will get the bounce back which is correct but when you put an integer in after "realizing your mistake" it gives it a 'NoneType' Class causing the test to fail because it is looking for an integer only.... Not sure how to proceed with this yet.

**Comment by erichelgeson** [comment]
Is the test you're referring to pushed up? Link to the line number here and show exactly what you expect.

**Comment by Jonas-Johnson** [comment]
It has been pushed up, I believe. Test_fizz_buzz.py I will work on figuring out how to link the line once I’m not on my phone.

**Comment by erichelgeson** [comment]
https://github.com/Jonas-Johnson/FizzBuzz/blob/main/Main/fizzbuzz.py#L4-L11
```python
def fizz_setup():
    try:
        fizz_input = int(input("What number do you want to use for Fizz? "))
        return fizz_input

    except ValueError:
        print("That is not a number, please try again.")
        fizz_setup()
```

first question to answer: what does this method return when `ValueError` happens?

**Comment by Jonas-Johnson** [comment]
https://github.com/Jonas-Johnson/FizzBuzz/blob/0896bab550d11e48140cb49e3ee26cdf2380ab90/Test/test_fizz_buzz.py#L13-L18

**Comment by Jonas-Johnson** [comment]
> 
> 
> https://github.com/Jonas-Johnson/FizzBuzz/blob/main/Main/fizzbuzz.py#L4-L11
> 
> ```python
> def fizz_setup():
>     try:
>         fizz_input = int(input("What number do you want to use for Fizz? "))
>         return fizz_input
> 
>     except ValueError:
>         print("That is not a number, please try again.")
>         fizz_setup()
> ```
> 
> first question to answer: what does this method return when `ValueError` happens?

Something bad because I'm calling the function that I'm already in... there is something cyclical about that, that isn't good I think

**Comment by Jonas-Johnson** [comment]
Correction, it doesn't return anything...

**Comment by erichelgeson** [comment]
* call `fizz_setup()`
* enter string "x"
* Exception of `ValueError`
* call `fizz_setup()` from except block
* enter int 1
* return 1 to *first* `fizz_setup()` - and *continue where it left off in the except block*
* No return statement in except (or after), so returns `None` to caller (main program)

This is recursion - kind of a complex concept but if you step through each line with your debugger attached you'll see how it works. I tried to find a tutorial but they are all bad and assume you know a lot of math.

**Comment by erichelgeson** [comment]
Light on content but compares looping vs recursion - and you can see in the graphic how recursion is different, you call "down the stack" then return back "up the stack" https://www.educative.io/edpresso/how-to-implement-the-fibonacci-sequence-in-python

**Comment by Jonas-Johnson** [comment]
I think we talked about that once, briefly... so what I need to do is to add a return of some sort in the except portion that will... something...

**Comment by erichelgeson** [comment]
Another approach is to loop until the input is valid - psudo code:
```
input = None
while input is None:
  try:
      input = ask for input
  except bad input
     print bad input, try again # input is still None, so loop will continue

return input
```

Only use recursion when you need to for math :)

**Comment by Jonas-Johnson** [comment]
woot! thanks
